build-nix-derivation:
  image: nixpkgs/nix:latest
  script:
    # Build the project including docs.
    - nix-build -A all
    - cp -r result-devdoc/share/gtk-doc/html/nautilus-python/ public/
  artifacts:
    paths:
      - public/

pages:
  stage: deploy
  dependencies:
    - build-nix-derivation
  script:
    - echo "Re-using public artifact from build job"
  artifacts:
    paths:
      - public/
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
